# Generated by Django 3.2 on 2026-03-22 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20260322_1735'),
        ('pharmacy', '0010_auto_20260304_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='accounts.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='accounts.city')),
                ('staff', models.ManyToManyField(blank=True, limit_choices_to={'role': 'PHARMACIST'}, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city__name', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pharmacy.store'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('store', 'medicine', 'batch_number')},
        ),
    ]
