# Generated by Django 3.2 on 2026-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20260322_1735"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allow_doctor_self_registration", models.BooleanField(default=True)),
                ("allow_pharmacist_self_registration", models.BooleanField(default=True)),
                ("doctor_approval_required", models.BooleanField(default=True)),
                ("pharmacist_approval_required", models.BooleanField(default=True)),
                ("expiry_alert_days", models.PositiveIntegerField(default=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
