# Generated by Django 5.0 on 2026-03-27 06:19

from django.db import migrations, models


def sync_existing_approval_status(apps, schema_editor):
    CustomUser = apps.get_model("accounts", "CustomUser")
    for user in CustomUser.objects.all():
        user.approval_status = "APPROVED" if user.is_approved else "PENDING"
        user.save(update_fields=["approval_status"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(sync_existing_approval_status, migrations.RunPython.noop),
    ]
