# Generated by Django 3.2 on 2026-03-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0011_auto_20260322_1735'),
        ('consultations', '0006_alter_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='assigned_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prescriptions', to='pharmacy.store'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='routing_status',
            field=models.CharField(choices=[('UNSENT', 'Unsent'), ('SENT', 'Sent')], default='UNSENT', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
