# Generated by Django 3.2 on 2026-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0007_auto_20260322_1735"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="routing_status",
            field=models.CharField(
                choices=[
                    ("UNSENT", "Unsent"),
                    ("SENT", "Sent"),
                    ("RECEIVED", "Received By Store"),
                    ("PARTIALLY_FULFILLED", "Partially Fulfilled"),
                    ("COMPLETED", "Completed"),
                ],
                default="UNSENT",
                max_length=20,
            ),
        ),
    ]
